enum CrystallCellType
{
	CUBIC_PRIMITIVE = 10, CUBIC_F, CUBIC_I,
	TETRAGONAL_PRIMITIVE = 20, TETRAGONAL_I,
	RHOMBIC_PRIMITIVE = 30, RHOMBIC_I, RHOMBIC_C, RHOMBIC_F,
	MONOCLINIC_PRIMITIVE = 40, MONOCLINIC_C,
	TRICLINIC_PRIMITIVE = 50,
	TRIGONAL_R = 60,
	HEXAGONAL_PRIMITIVE = 70
};
